### ISSUE TITLE
invokeMethodAsync is not a function.

### ISSUE THREAD

**Issue by mehmetuken** [ant-design-blazor/ant-design-blazor#1032]
AntDesign Nuget Version: 0.6.0-nightly-2101221736

<img width="624" alt="Screen Shot 2021-01-23 at 11 49 50" src="https://user-images.githubusercontent.com/9348193/105573808-38c42b80-5d71-11eb-938d-ba93e9510831.png">

**Comment by ElderJames** [comment]
Thanks for contacting us @mehmetuken .

Could you tell us how to reproduce this issue?  Which component are you using?

**Comment by mehmetuken** [comment]
My page have Table and modal component but this error coming i updated last nightly version. I use DataIndex future for my table. It's error coming randomly mouse move screen. It's not directly any component.

**Comment by anddrzejb** [comment]
This issue seems related to #1018 ant to [this comment](https://github.com/ant-design-blazor/ant-design-blazor/issues/1018#issuecomment-765236374). The thing is for me it fails on Vivaldi browser only with the same error but only on docs page, not during development...
Just to try to debug this further, could you @mehmetuken try it on a different browser?

**Comment by mehmetuken** [comment]
I using chrome. But i'm try now safari not showing console errors.

**Comment by mehmetuken** [comment]
And i'm clean all cache hard delete solved in the chrome.
