### ISSUE TITLE
Button property

### ISSUE THREAD

**Issue by boukenka** [ant-design-blazor/ant-design-blazor#1034]
### Is your feature request related to a problem? 
There is a short list of possible colors for the button background.

### Describe the solution you'd like
Could we add two more? Is it planned for the future?
A) '_warning_' (orange/yellow): Used for low-risk but not high-risk actions.
B) _'success_' (green): Used to finalize an action without any risk.

### Additional context
By the way, why are there warning messages from Visual Studio with the following code sample.
This is a copy/paste from [Ant Design Blazor Components](https://antblazor.com/en-US/components/overview).
The warning is as follows: _The warning "primary" is not a correct value of the attribute._
Is it possible to fix it? Is this normal?
I am using the build 0.6.0-nightly-2101221736 and VS 16.9.0 Preview 3.0.

```html
<div>
    <Button Type="primary">Primary</Button>
    <Button>Default</Button>
    <Button Type="dashed">Dashed</Button>
    <Button Type="link">Link</Button>
</div>
```
![Ant](https://user-images.githubusercontent.com/16502423/105625600-b13af300-5e2a-11eb-9afa-3a0384aac35b.png)

Thanks for any answer. 😄

**Comment by MutatePat** [comment]
Hello, this project is based of Ant Design for React. In their documentation, buttons do not have this feature. However you could add in-line CSS to solve this issue. In the future, we can add a colour parameter to the component which will do this for you.

Additionally, I have noted the issue with that VS warning. I believe the issue can be fixed by changing the Type parameter data type to "ButtonType". The class containing the types is already implemented but remains unused. This can be changed to an enum and we can use that on this parameter.

**Comment by boukenka** [comment]
Thank you @MutatePat for your answer.  I will wait for the '_future_'. 😄 

The programs below do not create a warning message.

```html
<div>
    <Button Type="@ButtonType.Primary">Primary</Button>
</div>
```
