### ISSUE TITLE
The ScrollY/ScrollX property of the table needs to support % and other units

### ISSUE THREAD

**Issue by rennner** [ant-design-blazor/ant-design-blazor#1046]
Table ScrollY  ScrollX 设置百分比的参数：%  vh vw不起作用 

```
<PageContainer >
    <ChildContent>
        <Card>
            <Table Style="margin-bottom: 5px;"  Bordered=@true Size=@TableSize.Middle
                   DataSource="@_tags" 
                   PageSize="100"   ScrollY="10%"  ScrollX="300"                   >

                <AntDesign.Column Title="参数名称" @bind-Field="@context.Name"  Width="100"/>
                <AntDesign.Column Title="标签ID" @bind-Field="@context.TagId" Width="100"/>
                <AntDesign.Column Title="标签类型" @bind-Field="@context.TagType" Width="80"/>
                <AntDesign.Column Title="当前值" @bind-Field="@context.StringValue" Width="100" Ellipsis />
                <AntDesign.Column Title="质量" @bind-Field="@context.Quantity" Width="80"/>
                <AntDesign.Column Title="时间" @bind-Field="@context.UpdateTime" Width="120"/>
                <AntDesign.Column Title="数据类型" @bind-Field="@context.StringType" Width="80"/>
                <AntDesign.Column Title="地址" @bind-Field="@context.Address" Width="150" Ellipsis/>

            </Table>

        </Card>
    </ChildContent>
</PageContainer>

```

**Comment by anddrzejb** [comment]
I had a look at this. % works as long as the parent has some kind of limit. From what I saw, the only sensible place to put the limit is in `Table` component. But `Style` parameter is not doing anything, so that probably needs to be fixed (@ElderJames I am not sure, it seems to me the `ant-table-container` is the right place but I am far from certainty). Regarding vh & vw for `ScrollY` - I had no problem with it, so I cannot confirm. `ScrollX` it is unclear to me what it should do, and the general logic is apparently different than `ScrollY`. From what I gathered - it is actually useful if you have any of the columns `Fixed`, so in this example it would not be useful anyway. 
@ElderJames On a side note - in `Table.razor` there is a separate rendering when `ScrollY` is set and separate when `ScrollX` is set. But it is exclusive, so if `ScorllY` is set, `ScrollX` will be omitted. Those renderings are quite different. At first it looked fishy to me, but without a really deep dive there (and clearly this is a complex component) I am just guessing.

**Comment by ElderJames** [comment]
This feature is a bit complicated because it involves the calculation of column widths. The current design, like react, is required to fix the width of each column.

I have done it at: 
https://github.com/ant-design-blazor/ant-design-blazor/blob/93064c03d032e9bd2a414ae69f9ccf950feab958/components/table/ColumnContext.cs#L70

If we need to support more units than px, we may have to try using the css `calc` function.
