### ISSUE TITLE
Implement i18n with IStringLocalizer

### ISSUE THREAD

**Issue by ElderJames** [ant-design-blazor/ant-design-blazor#1052]
Currently, we implement i18n with `LocaleProvider` and `LanguageService`.

`LocaleProvider` is for component itself, and `LanguageService` is for the docs.

At this issue, I think we can consider using `IStringLocalizer` for this, so that we can take advantage of .NET's own Localization framework.

[ASP.NET Core Blazor globalization and localization](https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-5.0&WT.mc_id=DT-MVP-5003987)

**Comment by ElderJames** [comment]
FYI https://medium.com/younited-tech-blog/json-based-blazor-localization-395b1b31e8ae

**Comment by anddrzejb** [comment]
Possibly a worth having a look at [https://blazorise.com/news/release-notes/093/#localization](https://blazorise.com/news/release-notes/093/#localization).
Mentions issues with `IStringLocalizer` I was not aware of.

**Comment by ElderJames** [comment]
Yeah, `IStringLocalizer` seems also not a good idea.

**Comment by anddrzejb** [comment]
@ant-design-blazor/committer, @MutatePat 

I am trying to figure localization out, as I think lack of fully featured localization is a big drawback. I do not believe the RTM should be released without the new approach that is able to:
- provide localization globally for all components
- provide localization for a single component only 
   - allow custom localization of a single component instance
   - allow localization for all instances of a single component
- allow adding localization resources "live" without the need to restart/recompile the application
   - globally (a localization that will alter all components - so a global site language change)
   - per component type (a localization that will alter language for all instances of a particular component)
   - per component instance (a localization that will alter language for a particular instance of a particular component)
- use json localization
- expose service to consumers, so it can also be used for custom components (not sure about that, it may be a big commitment, but if devs are going to use it, they will also help find the bugs)

Does this cover all the general features one would expect? 

_A small disclaimer: I can see that lack of localization is stopping me from working on enum support for `Checkbox` & `Select` (and probably other components as well). Just today I realized that `CheckboxGroup` cannot be used in `Form` component. I tried to patch it quickly but failed. Seems like it needs more work than I anticipated. I do not want to invest more time in it, since it may need a massive overhaul when adding enum support. I also believe all the input type components should probably be usable in `Form` component when RTM is released (after all `AntBlazor` is meant to be enterprise-class UI components). So here I came back to localization. I know there are other issues that were just patched instead of getting a proper fix, because localization is expected to change. Thus I believe this issue should probably be taken out of Backlog and moved to one of the milestones targeting releases before RTM._

**Comment by anranruye** [comment]
@anddrzejb Can not the current `LocaleProvider` do all these jobs?

**Comment by anddrzejb** [comment]
Possibly. Before I get to implementation details, I'd like to establish what are the broad requirements. So, planning first.

**Comment by Zonciu** [comment]
* Localization should fallback to English when the target language json file is not updated
* When Locale class is updated, it is better to update the json file for all languages, and the new fields are output in English, so that translators can easily know which localized fields have been added

**Comment by ElderJames** [comment]
Finally,  we implement the interactive StringLocalizer and Simple Json localization provider. #3804
