### ISSUE TITLE
TextArea sets value to null when field is empty.

### ISSUE THREAD

**Issue by NPadrutt** [ant-design-blazor/ant-design-blazor#1242]
### Describe the bug
I have a text area with a binding to a field of type string. When the text area is empty it doesn't set the value to string.empty but to null.

### Steps to reproduce (please include code)

This is the TextArea:

       <TextArea MinRows="3" @bind-Value="@context.Description" Type="string" />

And this is the model in abbreviated form:

```
public record CustomerProjectOverviewDto
    {
...
        public string Description { get; set; } = "";

...
    }
```

We close this issue when the correct default value is set.

### Further technical details
- AntDesign Nuget Package version
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by anddrzejb** [comment]
You are correct and I made a PR for your issue. But just a few points to your code:
- if you use records, you should not use setters; records by design should be immutable
- since records should be immutable, you should not use them as models for your forms; models should allow two-way binding which goes against record immutability
- `Type` parameter is actually useless for text area - `TextArea` component inherits from `Input` component, where `Type` is used to declare html type (input, password, number, etc);
