### ISSUE TITLE
'Input' component with the 'AutoFocus' property break the layout

### ISSUE THREAD

**Issue by henriquemotaesteves** [ant-design-blazor/ant-design-blazor#1312]
### Describe the bug

When the property 'AutoFocus' is enabled in the 'Input' component then the layout is breaked.

'Input' whithout 'AutoFocus':

!['Input' whithout 'AutoFocus'](https://user-images.githubusercontent.com/73287/113508969-75f32980-9529-11eb-8e47-107e676b5edd.png)

'Input' whith 'AutoFocus':

![Ant-2](https://user-images.githubusercontent.com/73287/113509008-a935b880-9529-11eb-9587-5fa03010527d.png)

### Steps to reproduce (please include code)

In the repository [Playground.Ant](https://github.com/henriquemotaesteves/playground/tree/csharp/ant%2F0.7.3) change the line 8 of the file [Authentication.razor](https://github.com/henriquemotaesteves/playground/blob/c24380aa98ea86866e86cc33b375838f731076f0/csharp/Playground.Ant/Playground.Ant/Pages/Authentication.razor#L8) by adding ou removing the 'AutoFocus" property.

### Further technical details

- Browser

![Ant-4](https://user-images.githubusercontent.com/73287/113509428-e26f2800-952b-11eb-93a0-09f13536bf8b.png)

- AntDesign Nuget Package version

0.7.3

- Include the output of `dotnet --info`

![Ant-5](https://user-images.githubusercontent.com/73287/113509507-60333380-952c-11eb-8885-4fe430e8159e.png)

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

![Ant-3](https://user-images.githubusercontent.com/73287/113509337-6b399400-952b-11eb-8ffb-9c62394cb0f9.png)

**Comment by anddrzejb** [comment]
I played around with your repro, and actually first thing I did was to remove your flex components. This immediately stopped the issue. However I was curious, so I decided to do the same, but with `AntBlazor` components, `Row` & `Col`. When I did that, all was good as well. Eventually, I tracked the issue to the fact, that your css has `width: 100%; height: 100%`. Normally I do not think this would be a problem, but apparently it is here, when you use it 2 times (and you are using your `flex` components twice). 
My recreation of the issue with only `AntDesign` components:
```razor
@page "/"
<AntDesign.Row Justify="center" Align="middle" Style="height: 100%; width: 100%;">
    <AntDesign.Col>
        <div class="authentication-page__form">
            <Form Layout="@FormLayout.Vertical" Model="@model">
                <FormItem Label="Username">
                    <Input @bind-Value="@context.Username" AutoFocus/>
                </FormItem>
                <FormItem Label="Password">
                    <InputPassword @bind-Value="@context.Password" />
                </FormItem>
                <FormItem>                    
                    <AntDesign.Row Justify="end" Align="middle">
                        <AntDesign.Col>
                            <div class="authentication-page__form__button">
                                <Button Type="@ButtonType.Primary" Block>Sign In</Button>
                            </div>
                        </AntDesign.Col>
                    </AntDesign.Row>
                </FormItem>
            </Form>
        </div>
    </AntDesign.Col>
</AntDesign.Row>

@code {

    private class UserModel
    {
        public string Username { get; set; }

        public string Password { get; set; }
    }

    private readonly UserModel model = new();
}
```

If you'd like to observe exactly the same problem, in line 13 add this style `Style="height: 100%; width: 100%;"`. It should have exactly the same effect as in your code.
@ElderJames This was still bugging me, because `AutoFocus` is just calling js `dom.focus();`. What I did in my tests, I switched to built in focus method (that appeared in net5) like this:
```csharp
        public async Task Focus()
        {
#if NET5_0
            await Ref.FocusAsync();                    
#else
            await JsInvokeAsync(JSInteropConstants.Focus, Ref);
#endif
        }
```
and the problem vanished... Maybe it would be a good idea to make a switch like that.

**Comment by ElderJames** [comment]
> Maybe it would be a good idea to make a switch like that.

I agree with you.
