### ISSUE TITLE
Filter does not pop up properly

### ISSUE THREAD

**Issue by Zonciu** [ant-design-blazor/ant-design-blazor#1405]
### Describe the bug

When `Table` does not set `OnChange` callback attribute, `Column Filter` does not pop up properly after being clicked.

When I change this [`Unbound`](https://github.com/ant-design-blazor/ant-design-blazor/blob/master/components/table/Column.razor#L182-L189) component to `ChildContent`, it works fine.

### Steps to reproduce

See [`DataIndex demo`](https://antblazor.com/en-US/components/table#components-table-demo-data-index) and [`Built-in Filter demo`](https://antblazor.com/en-US/components/table#components-table-demo-filter) 

### Further technical details
- AntDesign Nuget Package version: 0.8.0
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by ElderJames** [comment]
Is it a bug in the Unbound way or is it inherently limited? @anddrzejb

**Comment by anddrzejb** [comment]
I am investigating. It is clearly rendered, but with wrong coordinates. I will get back to you.

**Comment by anddrzejb** [comment]
The problem is in these lines https://github.com/ant-design-blazor/ant-design-blazor/blob/578e66d3254b6a644ba5de2cfe478aacf708a4f8/components/core/Component/Overlay/OverlayTrigger.razor.cs#L135-L143

If you replace them with these:
```csharp
        public ElementReference TriggerReference
        {
            get => Ref;
            set => Ref = value;
        }
```
it should start working.
Now here is some weird stuff happening - and I wonder how this might be related - in server side all seems to be working. But in wasm, in case of DataIndex demo, clicking on the filter opens the dropdown and closes it immediately. My quick tests shown that `Overlay.Hide()` method is called 3 times in wasm when I click on the filter button. In server-side no calls to that method are issued on first click. It is called 3 times on second click (maybe to many times, but hide methods should be called on 2nd click).
