### ISSUE TITLE
Select: OnDataSourceChanged event is not triggered when add or remove a single item, but it is triggered when clear the data source

### ISSUE THREAD

**Issue by anranruye** [ant-design-blazor/ant-design-blazor#1412]
### Describe the bug

OnDataSourceChanged event is not triggered when add a new item to data source. But it is triggered when remove an existed item.

### Steps to reproduce (please include code)

Use this demo: https://antblazor.com/zh-CN/components/select#components-select-demo-DefaultToggleDatasource. 

### Further technical details
- AntDesign Nuget Package version: 0.8.0, 0.8.1-nightly-2104211442

**Comment by anddrzejb** [comment]
I do not get the `OnDataSourceChanged` triggered neither when adding nor when removing. And if I understand correctly, this is the expected behaviour. The `OnDataSourceChanged` is triggered when `DataSource` object changes - I mean, a new instance of the object is attached. When adding/removing items to `IEnumerable`, the `DataSource` object is not being replaced with another.
@ElderJames is this the expected behaviour here? I do not see anything in react antD. Should we also call `OnDataSourceChanged` when items are added/removed?

**Comment by anranruye** [comment]
@anddrzejb  I agree that `OnDataSourceChanged` should be triggered only when the object reference which is hold by the `DataSource` property. However, it's strange that you don't notice the behavior I mentioned above.

Look at this:
![动画2](https://user-images.githubusercontent.com/54608128/115967116-5b7a0200-a563-11eb-8fd1-05b51f39a513.gif)

**Comment by anddrzejb** [comment]
Thanks for the time you spent on figuring this out! I will have a closer look and get back to you with the results.

**Comment by anddrzejb** [comment]
Ok, I think I have a solution. I will try to prep some test to cover this scenario. I should have a PR ready soon.
