### ISSUE TITLE
<Select> Very slow

### ISSUE THREAD

**Issue by mrcameron999** [ant-design-blazor/ant-design-blazor#1557]
### Describe the bug
Select component takes a very long time to open and feels very unresponsive

### Steps to reproduce (please include code)
Create a multi-select component and then publish the site
When you click on the select section it takes a good second or two to open. I don't get this issue on localhost but only on hosted sites. Is it to do with the latency and is there a way I can speed this up?

**Comment by anddrzejb** [comment]
I have several questions:
1. Wasm or server-side?
2. What is the size of the datasource (how many items)? If you limit the size of the datasource, do you see any improvement?
3. Does this happen on every select open or only on first time opening?
  - if it happens on every select open, do you see a difference between first time open and any consecutive open?

**Comment by mrcameron999** [comment]
> I have several questions:
> 
> 1. Wasm or server-side?
> 2. What is the size of the data source (how many items)? If you limit the size of the data source, do you see any improvement?
> 3. Does this happen on every select open or only on the first time opening?
> 
> * if it happens on every select open, do you see a difference between first time open and any consecutive open?


- I'm using Blazor Server
- The data source is no more than 4 items.
- Happens with every click

Here is a gif showing -I am clicking as soon as the cursor is over the box
Host: https://gyazo.com/90164d30244c6d3eba808d04691cf830

Local Host: https://gyazo.com/04a77d69aed78627726ed435b250bb76

Thanks for your help

**Comment by anddrzejb** [comment]
Well...I can see the problem. In my app it takes roughly 2sec to show the overlay regardless if I have 5 items or 450. So I do not think this is related to the number of items. If I run the same from localhost, then it is much faster (0.5sec?). This might be related to multiple re-renderings on open, but I am guessing now. I will try to have a look at this, but I do not have any time frame for this (currently overloaded with work).

**Comment by mrcameron999** [comment]
I have done some more experimenting and as I am using Cloudflare this is increased. It appears to me that when you click on the select it's going to the server and then a response is given back. What I'm confused about and forgive me if I am wrong I'm new to blazer surely the select could be stored in the user's browser instead of going to the server to ask to open the select?
Again I might be wrong and missing how blazer works when it comes to components like these

**Comment by anddrzejb** [comment]
There is a lot of things happening. It could be js<->.net communication to evaluate where the overlay needs to be open. I do not think the issue is with items - otherwise we would see a proportional increase of delay to items increase. But to be honest, at this stage it is too early to judge what is the problem. It needs a through and likely tedious research.

**Comment by ElderJames** [comment]
Perhaps the lite version (#1319)  will be needed before this problem can be completely solved

**Comment by anddrzejb** [comment]
I actually noticed the same problem in my app. It is working fine when in the local network, but over the VPN I get a really slow response. I also found [this issue](https://github.com/dotnet/aspnetcore/issues/19739) which might be related. I suspect I will have to put some extra hours to find out how we can fix this, as I will have a scenario when few of my customers are going to connect over the VPN. Obviously any help is appreciated.

**Comment by anddrzejb** [comment]
I was doing some work related to `DatePicker` and I ended up with figuring out what is going on here (or at least it seems to me that is the issue). 
@ElderJames , @mutouzdl this is for your attention and consideration. Please discuss your thoughts.
 So, the issue is of course network latency & the way the `Overlay` is currently designed. I actually did a deep dive into how `Overlay` is built and how can it be optimized. Aside the fact that there were multiple re-renderings happening, I found out that possibly our approach to invoking js is not the best. I actually run on my machine a test app (with just a simple `Dropdown` component), which I tested with a small tool locally and through a vpn on a computer that was around 5500km away (I used tracert & [traceroute mapper](https://stefansundin.github.io/traceroute-mapper/) to get rough estimate of how far away my second machine was) with average 110ms roundtrip response time. My measurements of execution times when running the site locally:

| Order | Execution / Total Execution Time | Source(File => Method: Line) | Comment |
| --- | --- | --- | --- |
|1 |  | Dropdown.razor.cs=>OnClickDiv: 71 |
| 2 | 1.1194ms/1.1194ms | OverlayTrigger.razor.cs=>OnTriggerClick: 643 |
|3 | 0.0332ms/1.1526ms | OverlayTrigger.razor.cs=>IsContainTrigger: 712 |
|4 | 0.1273ms/1.2799ms | Overlay.razor.cs=>IsPopup: 424 |
|5 | 0.7729ms/2.0528ms | OverlayTrigger.razor.cs=>Show: 792 |
|6 | 7.1265ms/9.1793ms | Overlay.razor.cs=>Show: 291 | About to Yield.
|     7 |      0.6366ms/9.8159ms | OverlayTrigger.razor.cs=>ShouldRender: 453 | _shouldRender = False(will change to 'true' here)
|     8 | 1.8565ms/11.6724ms | Overlay.razor.cs=>Show: 294 | After Yield | from step => 6
|     9 | 5.9411ms/17.6135ms | OverlayTrigger.razor.cs=>OnMouseUp: 681 | _mouseInOverlay = False && _mouseInTrigger = True
|    10 | 5.0263ms/22.6398ms | Overlay.razor.cs=>Show: 322 | continue 1 | from step => 6
|    11 | 0.2757ms/22.9155ms | OverlayTrigger.razor.cs=>ShouldRender: 453 | _shouldRender = True
|    12 | 0.0299ms/22.9454ms | Dropdown.razor=>BuildRenderTree: 7 | Dropdown < Childcontent > trigger rendering...
|    13 | 0.0958ms/23.0412ms | Dropdown.razor=>BuildRenderTree: 111 | Overlay rendering...
|    14 | 0.0221ms/23.0633ms | Overlay.razor.cs=>SetParametersAsync: 864 | Skipping...
|    15 | 0.0097ms/23.073ms | Overlay.razor.cs=>OnParametersSet: 846 |
|16 | 0.0087ms/23.0817ms | Overlay.razor.cs=>OnParametersSetAsync: 216 |
|17 | 0.2788ms/23.3605ms | Overlay.razor.cs=>ShouldRender: 199 | _shouldRender = True
|    18 | 0.0984ms/23.4589ms | Overlay.razor=>BuildRenderTree: 6 | Overlay(internal) rendering...
|    19 | 0.2069ms/23.6658ms | Overlay.razor.cs=>GetDisplayStyle: 782 | (rendering Overlay(internal))
|    20 | 0.2306ms/23.8964ms | Overlay.razor.cs=>GetOverlayCls: 764 | (rendering Overlay(internal))
|    21 | 0.3044ms/24.2008ms | OverlayTrigger.razor.cs=>GetPlacementClass: 752 |
| 22 | 0.7245ms/24.9253ms | Overlay.razor=>BuildRenderTree: 50 | Overlay(internal) rendering done | from step => 18
|    23 |     0.4166ms/25.3419ms | Overlay.razor.cs=>Ref: 838 | Ref is changing from NULL to cc6ffa7f-817c-4991-af80-7f71d3bd82f4
|    24 |     0.5938ms/25.9357ms | Overlay.razor=>BuildRenderTree: 20 | Overlay(internal) rendering... | from step => 18
|    25 | 24.8933ms/50.829ms | Dropdown.razor.cs=>OnAfterRender: 96 |
| 26 | 0.0261ms/50.8551ms | OverlayTrigger.razor.cs=>OnAfterRender: 462 |
|27 | 0.0083ms/50.8634ms | Dropdown.razor.cs=>OnAfterRenderAsync: 102 |
|28 | 0.0062ms/50.8696ms | OverlayTrigger.razor.cs=>OnAfterRenderAsync: 475 |
|29 | 0.012ms/50.8816ms | Overlay.razor.cs=>OnAfterRender: 853 |
|30 | 0.0076ms/50.8892ms | Overlay.razor.cs=>OnAfterRenderAsync: 232 | _isOverlayFirstRender = True
|    31 | 0.0126ms/50.9018ms | Overlay.razor.cs=>Show: 297 | Not Yielding.
|    32 | 4.7812ms/55.683ms | Overlay.razor.cs=>UpdateParentOverlayState: 748 |
|33 | 0.1124ms/55.7954ms | Overlay.razor.cs=>Show: 335 | continue 2 | from step => 31
|    34 | 0.8373ms/56.6327ms | Overlay.razor.cs=>AddOverlayToBody: 464 | Ref = cc6ffa7f - 817c - 4991 - af80 - 7f71d3bd82f4
|    35 | 3.6999ms/60.3326ms | Overlay.razor.cs=>Show: 337 | continue 3 | from step => 31
|    36 | 3.1386ms/63.4712ms | Overlay.razor.cs=>Show: 339 | continue 4, overlayElement dimensions obtained using JS | from step => 31
|    37 | 1.3214ms/64.7926ms | Overlay.razor.cs=>Show: 341 | continue 5, containerElement dimensions obtained using JS | from step => 31
|    38 | 0.9043ms/65.6969ms | Overlay.razor.cs=>GetOverlayLeftWithBoundaryAdjust: 485 |
| 39 | 0.8064ms/66.5033ms | Overlay.razor.cs=>GetOverlayLeft: 546 |
|40 | 1.7551ms/68.2584ms | Overlay.razor.cs=>BoundaryAdjust: 607 |
|41 | 1.9863ms/70.2447ms | Overlay.razor.cs=>GetWindowBoundarySize: 704 |
|42 | 15.9961ms/86.2408ms | Overlay.razor.cs=>GetOverlayDistanceFromBoundary: 685 |
|43 | 2.0829ms/88.3237ms | Overlay.razor.cs=>GetOverlayPosWithSize: 655 |
|44 | 1.7826ms/90.1063ms | Overlay.razor.cs=>GetOverlayTopWithBoundaryAdjust: 473 |
|45 | 0.7657ms/90.872ms | Overlay.razor.cs=>GetOverlayTop: 497 |
|46 | 0.3195ms/91.1915ms | Overlay.razor.cs=>BoundaryAdjust: 607 |
|47 | 0.019ms/91.2105ms | Overlay.razor.cs=>GetWindowBoundarySize: 704 |
|48 | 2.2153ms/93.4258ms | Overlay.razor.cs=>GetOverlayDistanceFromBoundary: 685 |
|49 | 0.9732ms/94.399ms | Overlay.razor.cs=>GetOverlayPosWithSize: 655 |
|50 | 9.4546ms/103.8536ms | Overlay.razor.cs=>GetTransformOrigin: 728 |
|51 | 0.2962ms/104.1498ms | OverlayTrigger.razor.cs=>GetOverlayEnterClass: 762 |
|52 | 0.7916ms/104.9414ms | Overlay.razor.cs=>ShouldRender: 199 | _shouldRender = True
|    53 | 0.038ms/104.9794ms | Overlay.razor=>BuildRenderTree: 6 | Overlay(internal) rendering...
|    54 | 0.0111ms/104.9905ms | Overlay.razor.cs=>GetDisplayStyle: 782 | (rendering Overlay(internal))
|    55 | 0.0139ms/105.0044ms | Overlay.razor.cs=>GetOverlayCls: 764 | (rendering Overlay(internal))
|    56 | 0.0156ms/105.02ms | OverlayTrigger.razor.cs=>GetPlacementClass: 752 |
|57 | 0.0164ms/105.0364ms | Overlay.razor=>BuildRenderTree: 50 | Overlay(internal) rendering done | from step => 53
|    58 |    0.0303ms/105.0667ms | Overlay.razor=>BuildRenderTree: 20 | Overlay(internal) rendering... | from step => 53
|    59 | 4.9014ms/109.9681ms | Overlay.razor.cs=>Show: 355 | continue  | from step => 31
|    60 | 1.2701ms/111.2382ms | Overlay.razor.cs=>OnAfterRender: 853 |
|  61 | 0.033ms/111.2712ms | Overlay.razor.cs=>OnAfterRenderAsync: 232 | _isOverlayFirstRender = False

This below table is exactly the same site, run on the same host, but this time on a remote computer over the vpn.
| Order | Execution / Total Execution Time | Source(File => Method: Line) | Comment |
| --- | --- | --- | --- |
1 |  | Dropdown.razor.cs=> OnClickDiv: 71 |
2 | 0.0539ms/0.0539ms | OverlayTrigger.razor.cs=> OnTriggerClick: 643 |
3 | 0.1976ms/0.2515ms | OverlayTrigger.razor.cs=> IsContainTrigger: 712 |
4 | 0.0203ms/0.2718ms | Overlay.razor.cs=> IsPopup: 424 |
5 | 0.0083ms/0.2801ms | OverlayTrigger.razor.cs=> Show: 792 |
6 | 0.0129ms/0.293ms | Overlay.razor.cs=> Show: 291 | About to Yield.
7 | 0.0431ms/0.3361ms | OverlayTrigger.razor.cs=> ShouldRender: 453 | _shouldRender = False(will change to 'true' here)
8 | 0.0449ms/0.381ms | Overlay.razor.cs=> Show: 294 | After Yield | from step => 6
9 | 3.1536ms/3.5346ms | OverlayTrigger.razor.cs=> OnMouseUp: 681 | _mouseInOverlay = False && _mouseInTrigger = True
10 | 113.4862ms/117.0208ms | Overlay.razor.cs=> Show: 322 | continue 1 | from step => 6
11 | 0.0512ms/117.072ms | OverlayTrigger.razor.cs=> ShouldRender: 453 | _shouldRender = True
12 | 0.0177ms/117.0897ms | Dropdown.razor=> BuildRenderTree: 7 | Dropdown < Childcontent > trigger rendering...
13 | 0.0904ms/117.1801ms | Dropdown.razor=> BuildRenderTree: 111 | Overlay rendering...
14 | 0.0159ms/117.196ms | Overlay.razor.cs=> SetParametersAsync: 864 | Skipping...
15 | 0.009ms/117.205ms | Overlay.razor.cs=> OnParametersSet: 846 |
16 | 0.0077ms/117.2127ms | Overlay.razor.cs=> OnParametersSetAsync: 216 |
17 | 0.0079ms/117.2206ms | Overlay.razor.cs=> ShouldRender: 199 | _shouldRender = True
18 | 0.013ms/117.2336ms | Overlay.razor=> BuildRenderTree: 6 | Overlay(internal) rendering...
19 | 0.0061ms/117.2397ms | Overlay.razor.cs=> GetDisplayStyle: 782 | (rendering Overlay(internal))
20 | 0.0055ms/117.2452ms | Overlay.razor.cs=> GetOverlayCls: 764 | (rendering Overlay(internal))
21 | 0.0123ms/117.2575ms | OverlayTrigger.razor.cs=> GetPlacementClass: 752 |
22 | 0.0113ms/117.2688ms | Overlay.razor=> BuildRenderTree: 50 | Overlay(internal) rendering done | from step => 18
23 | 0.0144ms/117.2832ms | Overlay.razor.cs=> Ref: 838 | Ref is changing from NULL to ebdc4ee8 - d7b8 - 4d10 - 995d - eea56df0c8cb
24 | 0.1803ms/117.4635ms | Overlay.razor=> BuildRenderTree: 20 | Overlay(internal) rendering ... | from step => 18
25 | 132.0287ms/249.4922ms | Dropdown.razor.cs=> OnAfterRender: 96 |
26 | 1.0224ms/250.5146ms | OverlayTrigger.razor.cs=> OnAfterRender: 462 |
27 | 0.3055ms/250.8201ms | Dropdown.razor.cs=> OnAfterRenderAsync: 102 |
28 | 0.0405ms/250.8606ms | OverlayTrigger.razor.cs=> OnAfterRenderAsync: 475 |
29 | 0.0138ms/250.8744ms | Overlay.razor.cs=> OnAfterRender: 853 |
30 | 0.0098ms/250.8842ms | Overlay.razor.cs=> OnAfterRenderAsync: 232 | _isOverlayFirstRender = True
31 | 0.016ms/250.9002ms | Overlay.razor.cs=> Show: 297 | Not Yielding.
32 | 120.8276ms/371.7278ms | Overlay.razor.cs=> UpdateParentOverlayState: 748 |
33 | 0.0434ms/371.7712ms | Overlay.razor.cs=> Show: 335 | continue 2 | from step => 31
34 | 0.0147ms/371.7859ms | Overlay.razor.cs=> AddOverlayToBody: 464 | Ref = ebdc4ee8 - d7b8 - 4d10 - 995d - eea56df0c8cb
35 | 117.7426ms/489.5285ms | Overlay.razor.cs=> Show: 337 | continue 3 | from step => 31
36 | 113.7686ms/603.2971ms | Overlay.razor.cs=> Show: 339 | continue 4, overlayElement dimensions obtained using JS | from step => 31
37 | 116.123ms/719.4201ms | Overlay.razor.cs=> Show: 341 | continue 5, containerElement dimensions obtained using JS | from step => 31
38 | 0.0418ms/719.4619ms | Overlay.razor.cs=> GetOverlayLeftWithBoundaryAdjust: 485 |
39 | 0.0095ms/719.4714ms | Overlay.razor.cs=> GetOverlayLeft: 546 |
40 | 0.0296ms/719.501ms | Overlay.razor.cs=> BoundaryAdjust: 607 |
41 | 0.0093ms/719.5103ms | Overlay.razor.cs=> GetWindowBoundarySize: 704 |
42 | 242.8033ms/962.3136ms | Overlay.razor.cs=> GetOverlayDistanceFromBoundary: 685 |
43 | 114.7346ms/1077.0482ms | Overlay.razor.cs=> GetOverlayPosWithSize: 655 |
44 | 0.0569ms/1077.1051ms | Overlay.razor.cs=> GetOverlayTopWithBoundaryAdjust: 473 |
45 | 0.0102ms/1077.1153ms | Overlay.razor.cs=> GetOverlayTop: 497 |
46 | 0.0098ms/1077.1251ms | Overlay.razor.cs=> BoundaryAdjust: 607 |
47 | 0.0069ms/1077.132ms | Overlay.razor.cs=> GetWindowBoundarySize: 704 |
48 | 230.5759ms/1307.7079ms | Overlay.razor.cs=> GetOverlayDistanceFromBoundary: 685 |
49 | 114.1266ms/1421.8345ms | Overlay.razor.cs=> GetOverlayPosWithSize: 655 |
50 | 120.4282ms/1542.2627ms | Overlay.razor.cs=> GetTransformOrigin: 728 |
51 | 0.125ms/1542.3877ms | OverlayTrigger.razor.cs=> GetOverlayEnterClass: 762 |
52 | 0.0905ms/1542.4782ms | Overlay.razor.cs=> ShouldRender: 199 | _shouldRender = True
53 | 0.0264ms/1542.5046ms | Overlay.razor=> BuildRenderTree: 6 | Overlay(internal) rendering...
54 | 0.0083ms/1542.5129ms | Overlay.razor.cs=> GetDisplayStyle: 782 | (rendering Overlay(internal))
55 | 0.0066ms/1542.5195ms | Overlay.razor.cs=> GetOverlayCls: 764 | (rendering Overlay(internal))
56 | 0.0104ms/1542.5299ms | OverlayTrigger.razor.cs=> GetPlacementClass: 752 |
57 | 0.0454ms/1542.5753ms | Overlay.razor=> BuildRenderTree: 50 | Overlay(internal) rendering done | from step => 53
58 | 0.047ms/1542.6223ms | Overlay.razor=> BuildRenderTree: 20 | Overlay(internal) rendering ... | from step => 53
59 | 0.241ms/1542.8633ms | Overlay.razor.cs=> Show: 355 | continue  | from step => 31
60 | 115.9457ms/1658.809ms | Overlay.razor.cs=> OnAfterRender: 853 |
61 | 0.0348ms/1658.8438ms | Overlay.razor.cs=> OnAfterRenderAsync: 232 | _isOverlayFirstRender = False

Notice that the total execution time for the remote request is 1658ms - over 1.5second (against 111ms so 0.1second locally). Mind that this is already after few optimizations on my part of the `Overlay` (originally I was getting over 600 lines with usually 3.6-4.2 seconds total execution time). 
You should also notice that there are several lines that their execution time is well over 100ms. This means that the method form previous line took the reported time to execute. For example:
- order 42 (line 42 in the table) reports 242.8033ms exection
- this mean that previous method from order 41 => `Overlay.GetWindowBoundarySize()` took actually 242.8033 to execute until `Overlay.GetOverlayDistanceFromBoundary()` was reached   

My investigation points me to js calls. Each js call actually takes over 100ms (this is for my case, where the network latency is 110ms) to execute. The logic that requests multiple calls is responsible for overlay positioning (with boundary detection). From what I can tell, the main issue here is that the js calls are being issued separately. For Wasm it does not really matter, but for server-side, this can be crucial, as this experiment of mine shows. There are 2 solutions here that I can see:
1. Bundle all js calls into a single call (well - not all-ALL, only the ones that are running as a single logic flow), so there is only a single call to js interop; every reposition/resize would also continue single calls (it would still probably create a visual hick-up when a lot of resize events were fired)
2. Move the appropriate logic completely to js, so only initializing call is executed, and future multiple repositioning is done using js events (without blazor)

Any other ideas? @ElderJames, you have the final word here in terms of the end solution applied - which would be better? I personally would opt for 2nd solution. As much as I do not like the idea of working with js, `AntBlazor` supposed to be enterprise level component library. We should strive to minimize the latency issues (which to the end users will look like half-baked solution). And with server-side, the latency is going to be everyday struggle.

**Comment by anranruye** [comment]
@anddrzejb Do you think it's possible to use only css to control overlay position and totally abandon js?

However, this means that we should implement the logic ourselves and no longer use the implementation of react antD.

**Comment by anddrzejb** [comment]
@anranruye I don't even know if we can do that with css. Maybe css3? But then IE support would suffer, wouldn't it? Mind that the overlay also detects if it needs to switch its position to be rendered above the triggering element (when for example the page scrolls to the position that would make overlay either invisible or partially visible). Could we achieve that with css only? I would be very interested in any solution you have in mind. Even if it is not going to make it to the final implementation.

**Comment by ElderJames** [comment]
@anddrzejb Thanks for the deep research, it's so amazing!

I've always found overlay to be a very complex component. Even though overlay is built-in in angular cdk, it's complex enough. And so far, only our component library has this component, which I'm proud of and very grateful for the contribution of @mutouzdl .

As the overlay became more and more complex, requiring more and more functionality, and after learning that it had so many and frequent dom operations, I agreed to use js to implement it. But the question is whether we have the ability to write it well. I suppose we could look to [popper](https://popper.js.org/) or [angular cdk](https://material.angular.io/cdk/overlay/overview) to do this.

**Comment by anddrzejb** [comment]
@ElderJames I don't really know if we have. I certainly do not have it yet. My starting point would be to try to mimic our current functionality. At this stage I started reorganizing our `interop.ts` into classes & modules. Once this gets accepted, I will start looking into how can we split the logic between blazor and js. My ultimate goal is to also include unit testing for js implementation (typescript). Maybe I will fail, but I think it is worth to try. 

What else we could do, is to first try to fix the blazor implementation (bundling of js calls) and then once done, move to implementing js solution. This smells to me like double work, but blazor fix would certainly be faster and simpler. Js work will definitely take me more time, as I am learning on the go. Also, that is why I am less active - this issue, as you said, is very complex and took me some time to "disassemble" it. I even created a semi-flowchart to actually better understand the logic behind obtaining position.

**Comment by mutouzdl** [comment]
@anddrzejb 
Overlay is a component that I started writing a long time ago, and it does get more complex and expose more problems. In addition to the performance issues, the coupling between Overlay and OverlayTrigger is too high.
Although I prefer plan 1, if you guys think plan 2 is better, that's fine with me.

Since I haven't used Blazor in my daily work, I don't have much time to study and I'm not good at performance optimization, so I don't have any more ideas for now.
 
I thought that when I started using Blazor for work in the future, I would become more familiar with it, so that I would be able to optimize the holes I had buried.
However, judging from the company's project schedule, it could be a long wait.
So, I really appreciate your contribution to the components.

--------------------- 中文  -------------------
Overlay是我很早之前就开始写的组件，确实越来越复杂，暴露的问题也越来越多。除了性能问题以外，Overlay和OverlayTrigger的耦合也太高了。  
虽然我更倾向于方案1，但如果你们觉得方案2更好，我也没有意见。  
由于我平时工作还没有用上Blazor，所以能研究的时间不多，对性能方面不擅长，暂时没有更多的想法。  
  
我原本想着未来工作上开始使用Blazor后，能对它更熟悉，我就有能力去优化之前埋下的这些坑。  
不过，从公司的项目安排来看，可能没那么快可以正式使用Blazor。  
所以，我非常感激你对相关组件做出的贡献。

**Comment by anddrzejb** [comment]
@mutouzdl I hope you are not taking my analysis as a criticism. I think you did and continue to do outstanding job! Without you, this project would not be the same. Blazor does seem to be more demanding due to the fact it offers different deployment models. This introduces more complexity - what works fantastic in wasm, requires extra work in server-side. The other way around is also true. As much as I also would prefer 1st approach, the latency will always be there for server-side. If we relay on constant trips to the server for dom calculations, in certain scenarios (for example rapid resizing) the latency will at the very least cause a delayed response and not a very appealing visual presentation. This is why I opt for 2nd option - which is bad news for me, because it will require js solution and I am not very comfortable using js (it is one of the reasons why I picked up blazor).  

I hope your company will decide to move to blazor (earlier than later).

**Comment by mutouzdl** [comment]
@anddrzejb 
Thank you for your acknowledgement. I don't take it as a criticism. In fact, I think you are seriously contributing to the project.
According to what you said, it seems plan 2 is more suitable.

Our boss has agreed to use Blazor, but we have not decided when we can start. I really hope we can use Blazor as soon as possible.

**Comment by anddrzejb** [comment]
@mrcameron999 Would you be so kind to test your project against 0.9.4 release and let us know if the speed has improved?

**Comment by mrcameron999** [comment]
> @mrcameron999 Would you be so kind to test your project against 0.9.4 release and let us know if the speed has improved?

Unfortunately, I no longer have the source for for that project with Ant Design. I will try give this a go in the not so distance future and report back my findings.
