### ISSUE TITLE
Select component will throw exception if the value is null

### ISSUE THREAD

**Issue by ldsenow** [ant-design-blazor/ant-design-blazor#1783]
I am on version 0.84.  My guess was one of my select option item's value field is null. This is kind of my fallback option.
Right now, I work around it by enabling AllowClear and Placeholder. 

In order to verify my assumption, I modified Select.OnDataSourceChangeTests and changed the Person's Id type to string and set it as null. When I ran the test, exception was thrown at line 684. I guess we need to handle null value comparison.

![image](https://user-images.githubusercontent.com/177045/127145051-48d406cf-20ab-4012-9ff5-b305faf74c21.png)

![image](https://user-images.githubusercontent.com/177045/127145875-56c5087c-bead-4e07-ab70-8d9b12bd1b03.png)

**Comment by anddrzejb** [comment]
@ElderJames I was thinking about this issue since it came up and I have few thoughts. Not yet sure how is this applicable, but I'd like to confront certain assumptions:
1. **Value, since it is a key, should not be null**: clearly, since you assigned me to this, I consider you accept that in this case it could be null.     
2. **Value, since it is a key, should be unique**: if we accept nullability of the value, next step is to accept the fact it is not unique. And I actually already have a use case for this: imagine a list of employees that belong to different groups (drivers, mechanics, office workers, etc). A single employee could potentially belong to more than 1 employee group. If we use group functionality of `Select`, we should be able to show the same employee (same key) multiple times belonging to different groups. And of course allow selecting them (I mean a selection of an employee in one group should also select all other occurrences of that employee).

I am not sure yet how to approach this problem, but I have a feeling we might need to introduce some kind of internal id (guid?) to actually manage unique item identification. We might also need to expose a method that will allow to customize selection logic. This approach however is very likely to introduce a major change to the `Select` component.

I also invite @anranruye, @Zonciu & anyone else to the discussion.

**Comment by ElderJames** [comment]
I'm prefer the key should be unique but can be nullable. 

If the same employee is in different groups, then just show which groups each employee is in. such as:

- Tom  (Group1, Group2)
- Jerry (Group1, Group3)

**Comment by anddrzejb** [comment]
I have a feeling you missed my point. I know I can do this, but I was also thinking about functional improvement of the select component (enhancement if you will) . If we accept  nullable value, how soon multiple nullable values are going to be requested? 

Anyway, I still have the whole overlay situation to deal with, so this issue is going to take me some time...

**Comment by ldsenow** [comment]
I think the value being null is a common scenario and have items with the same value as well.
Accepting null value is easy to resolve. I guess we all have solutions to it.

In order to resolve the same value issue, we could consider to expose the key generation expression to user if wanted to override the default behavior which uses the value as the key. Dont think we need to the component to make all the decisions, it is more or less on user's side to make sure the key are unique. Unless you tell me the component is looking for the item by value then it is something that needs to enhance.

**Comment by anranruye** [comment]
@anddrzejb Currently I don't think too much about not unique keys and exposing a method to customize selection logic. To solve the original issue, just need to change the code in the screenshot to `isSelected = value == _selectedValue || value?.Equals(_selectedValue) == true` .

**Comment by anranruye** [comment]
And I remember another issue: https://github.com/ant-design-blazor/ant-design-blazor/issues/1587#issuecomment-851896551 . If `null` is acceptable as the value, then the corresponding item should be selected when set the value to `null` or click the clear button.

**Comment by anranruye** [comment]
Since @anddrzejb is busy, I opened a pr. However, we should also solve #1587 for this scenario. Otherwise, the `Select` component will display empty or placeholder text when the option with null value is selected.
