### ISSUE TITLE
Layout Component Style Bug

### ISSUE THREAD

**Issue by pp-tang** [ant-design-blazor/ant-design-blazor#1822]
### Describe the bug

 Layout Class="app-layout"  don't find in "MainLayout.razor.css",  but in "MainLayout.razor" style is worked.

.app-layout {
  height: 100%;
}

### Further technical details
- AntDesign Nuget Package version 0.9.0

**Comment by dennisrahmen** [comment]
Cloud you share more information on your problem?

Is you problem regarding CSS isolation? Is so, this issue may help you:
https://github.com/ant-design-blazor/ant-design-blazor/issues/732#issuecomment-739125806

**Comment by ElderJames** [comment]
@dennisrahmen Would you please to help improve the FAQ document?

**Comment by dennisrahmen** [comment]
@ElderJames Sure, I will look into it next week.

Maybe you could also think about moving the Wiki from GitHub to the Docs section on antblazor.com, so there is only one stop to check if a question was already asked and answered.
Then you could link the Docs in the GitHub Wiki.

I could also add a "Wiki" section to the Docs but would need help with the contents of the current GitHub Wiki since it is mostly in chinese.

**Comment by dennisrahmen** [comment]
The issue can be closed, since the explanation has been added to the documentation.

**Comment by ElderJames** [comment]
Ok, thanks @dennisrahmen .
