### ISSUE TITLE
Searching by date adds the current time

### ISSUE THREAD

**Issue by kuznecovIT** [ant-design-blazor/ant-design-blazor#1828]
### Describe the bug

If I use search by only date, 
I would like have the passed value in `QueryModel<Data> query`, without the added time.

**Is it possible to somehow specify only the date without time (or with time set to 00:00:00)?**

With a green circle, I marked on screenshot below the time that I talk about and which would like to set to 00:00:00 while i use search only by date.

### Steps to reproduce (please include code)
Used example from https://antblazor.com/en-US/components/table#components-table-demo-filter
![image](https://user-images.githubusercontent.com/62954135/128636386-9ec213ac-65d1-4770-90ce-87593ed6f9e6.png)

**Comment by dennisrahmen** [comment]
This is probably a limitation of C#, there is currently only "DateTime" as datatype, so the time will always be attached to the date.

I think it is best to wait with this till .NET 6 is released, since in .NET 6 the DateOnly and TimeOnly types are added.
https://devblogs.microsoft.com/dotnet/date-time-and-time-zone-enhancements-in-net-6/#introducing-the-dateonly-and-timeonly-types

**Comment by kuznecovIT** [comment]
> This is probably a limitation of C#, there is currently only "DateTime" as datatype, so the time will always be attached to the date.
> 
> I think it is best to wait with this till .NET 6 is released, since in .NET 6 the DateOnly and TimeOnly types are added.
> https://devblogs.microsoft.com/dotnet/date-time-and-time-zone-enhancements-in-net-6/#introducing-the-dateonly-and-timeonly-types

I do not mind that the time was attached to the date (although I would like to have a type without time at the moment...), 
I just would like to understand why it is not set at 11/1/1977 00:00:00 (In the above example, unnecessary time is added which further interferes with data processing)

**Comment by anranruye** [comment]
@kuznecovIT thanks for contacting us.

In the new released 0.9.1 version, we set `ShowTime=true` for the DatePicker component in the filter so that you can now control the attached time. We will add a new table filter type `DateEquals` to solve the date-only scenario in the future.

The related DatePicker issue is tracked by this process: #1277

**Comment by anranruye** [comment]
You can now use the new `SameDate` filter type to only compare the Date part.
