### ISSUE TITLE
Overlay is not in the correct position when the menu component is in the contracted state 

### ISSUE THREAD

**Issue by WTUIYV** [ant-design-blazor/ant-design-blazor#1836]
### Describe the bug

Overlay is not in the correct position when the menu component is in the contracted state 

### Steps to reproduce (please include code)

You need to slide the mouse over the shrink menu
### Exceptions (if any)

<img width="821" alt="Snipaste_2021-08-13_11-11-16" src="https://user-images.githubusercontent.com/10544601/129299988-79bea212-4ac9-4fef-9258-ca97bb300468.png">
<img width="482" alt="Snipaste_2021-08-13_11-16-18" src="https://user-images.githubusercontent.com/10544601/129300047-669a69c9-38e4-4f30-bd7b-93fbbbb564ac.png">

### Further technical details
- AntDesign Nuget Package 0.9

**Comment by anddrzejb** [comment]
I cannot recreate that with the current docs. I tried on firefox (90.0.2 & 91.0), chrome (92.0.4515.131) & edge (92.0.902.67). Can you try to refresh cache on your browser? If that wont help, can specify what browser & version are you using?

**Comment by anddrzejb** [comment]
Ok, I managed to recreate this issue. It started happening once I did a lot of mouse movement. The fix is coming in my major overlay overhaul. The overhaul is functionally ready, now I need to optimize it and clean up the code. This may take me some time, especially that I will have to leave for couple of days soon.
