### ISSUE TITLE
Icons not rendering and icons docs not loading

### ISSUE THREAD

**Issue by binbsr** [ant-design-blazor/ant-design-blazor#192]
I am experimenting blazor UI libraries these days. After going through initial setups and basic elements. I am stuck playing with icons.

1. Got "Menu" control rendered but the icons on menu items, not sure if I have to do anything special for AntIcons.

1. [Icon docs](https://ant-design-blazor.gitee.io/en-US/icon) not loading for me, tried many times in different browsers but just getting following:
![image](https://user-images.githubusercontent.com/1488017/83906541-7abd4480-a783-11ea-883b-63b9b67fb5c7.png)

Can anyone help me please?

**Comment by ElderJames** [comment]
Thank you for contacting us @binbsr.
Because the icon component was created a long time ago, in 3.x, it is different from the official 4.x version. We are about to upgrade to 4.x again.
The type of icon can be referred to the [ng-zorro-antd](https://ng.ant.design/components/icon/en) document, select the icon you need.
We will update and provide the documentation as soon as possible.I apologize for the inconvenience.
