### ISSUE TITLE
The modal dialog cannot be displayed using @ref

### ISSUE THREAD

**Issue by wf-soft** [ant-design-blazor/ant-design-blazor#1982]
I want to use "ref" to access the "showmodal" method, but it doesn't seem to work and the dialog box doesn't display

```
<AddClearTask @ref=@addClearTask/>
<AddConvertTask @ref=@addConvertTask/>
<div style="margin-bottom:20px">
    <Button Type="primary" OnClick="@ShowAddClearTask">Btn1</Button>
    <Button Type="primary" OnClick="@ShowAddConvertTask">Btn2</Button>
</div>
@code {
    AddClearTask addClearTask;
    AddConvertTask addConvertTask;
    async Task ShowAddClearTask()
    {
        await addClearTask.ShowModal();
    }
    void ShowAddConvertTask()
    {
        addConvertTask.ShowModal();
    }
}
```

![image](https://user-images.githubusercontent.com/62228539/135237869-ab2b36af-7f11-4012-b777-0be50618a84a.png)

**Comment by anranruye** [comment]
Well, I think this is caused by blazor render mechanism.

Since `AddClearTask` has no paramter, blazor will skip the render of this component after `ShowAddClearTask()` method is called.

You can add `StateHasChanged();` after _visible = true.

A better solution is to use a `ModelVisible` paramter to control the modal, rather than a method.

**Comment by wf-soft** [comment]
@anranruye You are right. Statehaschanged() is used to solve this problem. The main reason is that the async method is required in showmodal(), so it is inconvenient to use await in the visible attribute, Thank you
