### ISSUE TITLE
[Overlay] The dropdown of cascader doesn't open when the input was clicked.

### ISSUE THREAD

**Issue by ElderJames** [ant-design-blazor/ant-design-blazor#2111]
### Describe the bug

I think this is because there is no trigger to refresh, when moving the mouse to an element that has a trigger event, the dropdown will open. @anddrzejb Have you seen this?

![cascader-dropdown](https://user-images.githubusercontent.com/7550366/141721947-fa986226-5e2b-454e-b7d9-506fac893994.gif)

### Steps to reproduce (please include code)

Just in demo.

### Further technical details
- AntDesign Nuget Package version 0.10.2
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version

**Comment by anddrzejb** [comment]
That's possible. I will try to have a look. I was trying to optimize triggering (something I complained about in #1130), but I failed (or rather gave up due to lack of time and progress). What I found out is that we are having inconsistent way of triggering. There is a triggering logic built into `OverlayTrigger` that supposed to be common. But a lot of other components (like `Select`, `DatePicker`, `Cascader`) are using their own logic to open the overlay. So we end up with a situation that we have several techniques to do the same, sometimes one battling another. Very hard to reason about and to maneuver. Sadly I am completely swamped.
