### ISSUE TITLE
Transfer Component can’t select item when click in v0.13.3

### ISSUE THREAD

**Issue by xccu** [ant-design-blazor/ant-design-blazor#3008]
### Transfer Component can’t select item when click in v0.13.3

in v0.13.3 when using <Transfer> Component , no response when select items in source and target 
while in v0.13.0 to v0.13.2,  select items are normal

### Code(Same as Basic Example in Doc
   ```csharp
   <div>
    <Transfer DataSource="_dataSource"
              Disabled="_disabled"
              TargetKeys="_targetKeys.ToArray()"
              SelectedKeys="_selectedKeys"
              Titles="_titles"
              OnChange="OnChange"
              OnScroll="OnScroll"
              OnSelectChange="OnSelectChange">
    </Transfer>

    <Switch Style="margin-top: 16px;" OnChange="OnSwitchChange"></Switch>
</div>

@code {
    private List<TransferItem> _dataSource = new List<TransferItem>();
    private List<string> _targetKeys = new List<string>();
    private string[] _selectedKeys = Array.Empty<string>();
    private string[] _titles = { "Source", "Target" };
    private bool _disabled = false;

    protected override void OnInitialized()
    {
        for (int i = 0; i < 20; i++)
        {
            _dataSource.Add(new TransferItem
            {
                Title = $"Content{i + 1}",
                Description = $"description of content{i + 1}",
                Key = i.ToString(),
                Disabled = i % 3 < 1
            });

            if (i > 10)
                _targetKeys.Add(i.ToString());
        }
        base.OnInitialized();
    }

    private void OnSwitchChange(bool check)
    {
        _disabled = check;
    }

    private OneOf.OneOf<string, RenderFragment> Render(TransferItem item)
    {
        return $"{item.Title} - {item.Description}";
    }

    private void OnChange(TransferChangeArgs e)
    {
        Console.WriteLine(e.Direction);
        Console.WriteLine($"MoveKeys:{string.Join(',', e.MoveKeys)}");
        Console.WriteLine($"TargetKeys:{string.Join(',', e.TargetKeys)}");
    }

    private void OnScroll(TransferScrollArgs e)
    {
        Console.WriteLine(e.Direction);
    }

    private void OnSelectChange(TransferSelectChangeArgs e)
    {
        Console.WriteLine($"SourceSelectedKeys:{string.Join(',', e.SourceSelectedKeys)}");
        Console.WriteLine($"TargetSelectedKeys:{string.Join(',', e.TargetSelectedKeys)}");
    }
}
)
```
![issue](https://user-images.githubusercontent.com/7534189/211777679-cde42500-73b8-4789-9019-478477858fe9.png)

**Comment by ElderJames** [comment]
Hello @Magehernan , could you please help me look at this problem? I think it was your previous pr that caused it.
https://github.com/ant-design-blazor/ant-design-blazor/pull/2977

When a item was clicked, transfer would call RefreshKeys and the `SelectedKeys` parameter still is empty.

**Comment by ElderJames** [comment]
The SelectedKeys and TargetKeys would set the original value every time the transfer render, so we can refresh keys in 'SetParametersAsync'. I think we need to add a public Method to reload the component.

**Comment by Magehernan** [comment]
Hi i will look at it

**Comment by Magehernan** [comment]
> Hello @Magehernan , could you please help me look at this problem? I think it was your previous pr that caused it.
> #2977

i check going back 1 commit before and it works, so in my project works fine but i wasn't using selectKeys, so i will fix it.

**Comment by Magehernan** [comment]
> The SelectedKeys and TargetKeys would set the original value every time the transfer render, so we can refresh keys in 'SetParametersAsync'. I think we need to add a public Method to reload the component.

I add this feature like a year ago, i was wanting to send it like this with a manual method, but is more complex to unserstand.

@ElderJames i found the problem with the examples and why this is broke on the example plage but is working really good on my web. 
The problem i found is in the example
https://github.com/ant-design-blazor/ant-design-blazor/blob/e41b89c2768ea4f54cdbd3cc56d046ce247d315a/site/AntDesign.Docs/Demos/Components/Transfer/demo/Basic.razor#L2-L10

because in line 4, _targetKeys is using .ToArray() every time it refresh it make the example restart because the array is not the same as was before.

I change the type of target keys to string[] and then make a list on the code before, calculate and in the end added _targetKeys = keys.ToArray(); and with that is works greate.

https://github.com/ant-design-blazor/ant-design-blazor/blob/e41b89c2768ea4f54cdbd3cc56d046ce247d315a/site/AntDesign.Docs/Demos/Components/Transfer/demo/Basic.razor#L22-L38

so i think that the examples are a little bad about creating a new array every time the state change... if i change the examples it will work fine and if you make a new array every time it will reset because of that you can update the extenal array and it will update without needed to call a manual method.

**Comment by Magehernan** [comment]
another thing, i look that the method InitData i put it on the RefreshKeys, it needed to be on the OnInitialized like it was before, is not needed to refresh the inicial internal values any time the keys change.

**Comment by ElderJames** [comment]
Thank you @Magehernan .
