### ISSUE TITLE
Problem with expanding tables and 0.17.2

### ISSUE THREAD

**Issue by notsonormal** [ant-design-blazor/ant-design-blazor#3621]
There is a problem in 0.17.2 related to expanding a row in a table. 

If you look at your expanding demo for the table component, you can see that while expanding an individual row does work the Expand All button does not work properly. Expand All does not expand any rows, rather it actual collapses all rows. 

https://antblazor.com/en-US/components/table#components-table-demo-expand

I have a different problem in my code where clicking the plus button doesn't expand the row at all. I haven't made a "minimalistic repro project hosted in a GitHub repo" because I'm hoping if you fix the first issue then it will fix my issue as well.

My issue does not happen in 0.17.1. I'm not sure about the issue with the demo page.

**Comment by nijdamb** [comment]
For me this issue seems to have something to do with the OnExpand="" option on the Table component.
Whenever I remove the OnExpand="" parameter the rows expand fine. 
Even if the eventcallback function that OnExpand calls is nothing special, as soon as I add the OnExpand parameter with a callback function the expansion stops working.
