### ISSUE TITLE
[Select] Please add TValue for value type conversion

### ISSUE THREAD

**Issue by Yuanxw612** [ant-design-blazor/ant-design-blazor#724]
The select value type is String, the actual business has other types, and you want to add TValue to specify the value type.

```
<Select TValue="int">
</Select>
```

@ElDiddi

**Comment by ElDiddi** [comment]
Hello Yuanxw,

I think that `TValue` is difficult to implement in the current `select` module. Users can create their own tags, if `TValue` is an `integer`, which value should be set automatically? If you only allow `GUID` and `string` you can have the `GUID` generated automatically and if you allow `string` you can use the label value. Whereby `string` can generate an error if the `value` of the label corresponds to an existing value.

The easiest way would be to have two different modules, one that corresponds to a normal ComboBox with the usual WPF parameters like DataContext, SelectedItem, SelectedValue, ItemTemplate etc. and one that allows tags that only support `GUID` as value. Another approach would be to support only `GUID` in the current `select` module.

The current approach is for me at least a little bit difficult to maintain, because you have to pay attention to all combinations.

@ElderJames 
Do you have an idea? Maybe I think in the wrong direction.

Kind regards

**Comment by Yuanxw612** [comment]
If the TValue doesn't fit,I think you can just use enumerations, @ElDiddi  @ElderJames  what do you think?
```
<Select ValueType="@SelectValueType.Guid">
</Select>
```

**Comment by ElDiddi** [comment]
Hi @Yuanxw612,

sorry for the delay. I am working on this module intensively in my spare time. Maybe I will be able to send the PR by the weekend.

**Comment by Yuanxw612** [comment]
@ElDiddi you did great!

**Comment by ElDiddi** [comment]
Hey @Yuanxw612,

i send the PR for the select modul with alot of new features. Maybe you can test it and report some issues if you find any.
Take a look to the rewritten demos for this module, because the databinding has changed.

https://github.com/ant-design-blazor/ant-design-blazor/pull/786
https://github.com/ElDiddi/ant-design-blazor/tree/select-rewritten1

**Comment by Yuanxw612** [comment]
@ElDiddi The complete rewrite of the SELECT component is exciting. i was touched by your contribution . good
