### ISSUE TITLE
Problem with the Style attribute in the Input component

### ISSUE THREAD

**Issue by szmalec** [ant-design-blazor/ant-design-blazor#876]
### Describe the bug
Component Input with the `Style` attribute may render differently depending on additional attributes, eg `AllowClear`.

### Steps to reproduce (please include code)
```
<Input Placeholder="Enter text" @bind-Value="_txt" Style="text-align: center" />

<Input Placeholder="Enter text" @bind-Value="_txt" Style="text-align: center" AllowClear />

@code {
    private string _txt = "Lorem ipsum...";
}
```

![image](https://user-images.githubusercontent.com/7856921/101612827-5fb9de80-3a0b-11eb-8328-dacfd0dc77e8.png)

As you can see, adding the `AllowClear` attribute resulted in wrapping the `input` tag in an additional `span` tag and the style passed in the `Style` parameter is applied to this `span` tag instead of the `input` tag. Shouldn't it work consistently in both cases?

### Further technical details
Problem in: 0.5.0-nightly-2011180810 and also in 0.5.0-nightly-2012081156

**Comment by anddrzejb** [comment]
@ElderJames I was trying to tackle this issue but I think we have a general design problem here. As @szmalec pointed out, there is an extra `<span>` wrapping the `<intput>`, which is fine - react antdesign does exactly the same. The `<input>` is wrapped in extra `<span>` whenever there is any extra functionality added to the `<input>` (prefix/suffix/password/search/inputgroup/etc). The problem here is that for a consumer, the component is a single element, but reality is that it can be couple of different elements. So some of the styles that a consumer would like to apply to the element, should end up either in `<span>` or in `<input>`. 
For example if a consumer of an `<Intput AllowClear>` component would like to pass `Style="text-align: center; width: 30%"`, then the `text-align` style should be applied to `<input>`, while `width` should be applied to `<span>`. How do we detect which belongs where? There are 3 options I can currently think of:
1. Hardcode which styles should apply to which element - I do not like this solution. It is a lot of work and checking a string for all possible occurrences is not the most efficient way of doing things.
2. Split the `Style` attribute into `StyleInternal` and `StyleExternal` (the names are not really a proposal, but I needed to use something just to present the idea). So `StyleInternal` would be applied to `<input>` and `StyleExternal` to `<span>`. I do not like this idea either, as it is very unintuitive and for regular `Input` without any extra functionality (the one that does not generate `<span>` wrapper) the `StyleExternal` would be useless (and would probably be a source of a lot of issues in this repo). 
3. Add attributes that would serve only to style `<input>`, for example `Center`, `Font`, etc. I think this is the idea I dislike the least. We could probably add those as more request are coming. It still would be confusing, but hopefully less than idea 2. 

I do hope there are better ideas on how to solve this problem.

**Comment by ElderJames** [comment]
I think we can add `WrapperStyle` for span wrapper.
